### ISSUE TITLE
Steam Group Kicker doesn't seem to play well

### ISSUE THREAD

**Issue by ghost** [GentlePuppet/Gentles_Tampermonkey_Userscripts#1]
Googled to eventually find an outdated script, with [a link to yours](https://github.com/GentlePuppet/Gentles_Tampermonkey_Userscripts/blob/main/Steam%20Group%20Mass%20Kicker/Steam%20Group%20Mass%20Kicker%20Script.user.js), tried it, didn't work. removed some parts on my own, still didn't work.
using tampermonkey on latest chrome, here's console log
![image](https://github.com/GentlePuppet/Gentles_Tampermonkey_Userscripts/assets/45308130/ab893989-f9bd-4b26-ba18-1b3204d37371)

**Comment by GentlePuppet** [comment]
I don't know what you changed but that error doesn't occur for me and the script works as intended and doesn't have any errors that stops it from working. I regularly use this script to purge bot/scam accounts from one of the groups I moderate.

Did you click on the checkbox next to the kick button to select each user you wanted to kick and then clicked the kick button at the top?

**Comment by ghost** [comment]
tried vanilla, same thing removed the side-profile and a few unnecessary functions at the start that were commented: still the same thing, tried it in hopes of "ah yes surely it's just these few lines causing issues"

**Comment by GentlePuppet** [comment]
I am unable to replicate this issue and when using my script to clear out a few more bots from my group without error I can say I have no idea what could possibly be going wrong for you...

I have no action for changing players ranks like in yer error `onclick*=ManageMembers_ToggleRank`
And I did some testing with changing a players ranks from member to moderator back to member and I never got this error.

What did you do when you were using this script.
Step by step what were yer actions that you took to cause this error?

**Comment by ghost** [comment]
installed > refresh manage members page (no page in url) > select a couple
> kick them with the button > nothing happens

**Comment by GentlePuppet** [comment]
Ah, I figured out what is happening. An oversight on my part, the error occurs if you have permission to change the rank of users.

Kicking normal, non-promoted users, works as intended however.

When I get home from work I will work on fixing this issue.

**Comment by ghost** [comment]
"at some point"... double checked that I selected random people that were always regular members, still didn't work

on another note, just realized that if you spam kick and enter with tiny intervals on web, you can get a lot of people out without autorefreshes that steam does

**Comment by GentlePuppet** [comment]
I know the issue and I'm working on a fix, I might be able to patch it before I have to go to work in 20 minutes.

**Comment by GentlePuppet** [comment]
Fixed the issue with a simple solution by changing the profile_url selector to be more precise.

From: `$(this).parents('.member_block').find('img.manageMemberAction')`
To: `$(this).parents('.member_block').find('img[onclick*=ManageMembers_Kick]')`
